name: TFLint

on:
  - pull_request
  - push

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set-up TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2

      - name: Run TFLint
        run: tflint --recursive --format=compact
