name: TFLint

on:
  - pull_request
  - push

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set-up TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0

      - name: Run TFLint
        run: tflint --recursive --format=compact
