name: TFLint

on:
  - pull_request
  - push

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set-up TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2

      - name: Run TFLint
        run: tflint --recursive --format=compact
